import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getSession, signIn, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { redirectIfUserIsAuthenticated } from "../helpers/redirect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + " " + inter.className}>
        <button onClick={() => signIn()}>Get started</button>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  return redirectIfUserIsAuthenticated({ context, path: "/home" });
}
