import Head from "next/head";
import { signIn } from "next-auth/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          height: "100vh",
          justifyContent: "center",
          alignContent: "center",
        }}
      >
        <button onClick={() => signIn()}>Get started</button>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return {
    redirect: {
      destination: "/home",
      permanent: false,
    },
  };
}
